U ?= $(shell pwd)/../..

include $(U)/mk/bootstrap.mk
include $(MAKEDIR)/sugarTop.mk

include_DUALHEADERS= \
	generic/connection.h \
	generic/crypto.h \
	generic/envelope.h \
	generic/ethernet.h \
	generic/ip.h \
	generic/netCrypto.h \
	generic/net.h \
	generic/netInterface.h \
	generic/netStackPosix.h \
	generic/networking.h \
	generic/packetEncoder.h \
	generic/packet.h \
	generic/reliabilityWindow.h \
	generic/rpc.h \
	generic/rtt.h \
	generic/tunnel.h \
	generic/udp.h \

include $(MAKEDIR)/sugarBottom.mk
